name: Publish Frontend Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Definir versão da imagem com base na execução
        run: echo "IMAGE_VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da imagem Docker (Angular)
        run: |
          docker build -t ghcr.io/domnum/front:${{ env.IMAGE_VERSION }} \
                       -t ghcr.io/domnum/front:main \
            --build-arg BACKEND_URL=${{ secrets.BACKEND_URL }} \
            --build-arg API_KEY=${{ secrets.API_KEY }} \
            -f Dockerfile .

      - name: Push da imagem versionada
        run: docker push ghcr.io/domnum/front:${{ env.IMAGE_VERSION }}

      - name: Push da imagem com tag main
        run: docker push ghcr.io/domnum/front:main
