name: Publish Frontend Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Definir versão da imagem com base na execução
        run: echo "IMAGE_VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm ci

      - name: Build Angular
        run: npm run build -- --configuration production

      - name: Gerar env.js com variáveis
        run: |
          echo "window['env'] = {" > ./dist/front/env.js
          echo "  BACKEND_URL: '${{ secrets.FRONTEND_BACKEND_URL }}'," >> ./dist/front/env.js
          echo "  API_KEY: '${{ secrets.FRONTEND_API_KEY }}'" >> ./dist/front/env.js
          echo "};" >> ./dist/front/env.js

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build da imagem Docker (NGINX + dist)
        run: |
          docker build -t ghcr.io/domnum/front:${{ env.IMAGE_VERSION }} \
                       -t ghcr.io/domnum/front:main \
                       -f Dockerfile .

      - name: Push da imagem versionada
        run: docker push ghcr.io/domnum/front:${{ env.IMAGE_VERSION }}

      - name: Push da imagem com tag main
        run: docker push ghcr.io/domnum/front:main
