name: Publish Frontend Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Definir versão da imagem com base na execução
        run: echo "IMAGE_VERSION=1.0.${{ github.run_number }}" >> $GITHUB_ENV

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run build.sh to build Docker image
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Login no GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push da imagem com tag versionada
        run: docker push ghcr.io/domnum/front:1.0.${{ github.run_number }}

      - name: Push da imagem com tag main
        run: docker push ghcr.io/domnum/front:main

      - name: Disparar deploy no repositório ci-cd
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.CICD_TRIGGER_TOKEN }}
          repository: domnum/ci-cd
          event-type: deploy-domnum
          client-payload: '{"service":"frontend"}'
